version: "3.8"
services:
  db:
    image: mariadb:latest
    container_name: db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: masterroot
      # MARIADB_DATABASE: fast_api_tc_psn
      MARIADB_USER: root
      MARIADB_PASSWORD: masterroot
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 10s
    #   retries: 5
    platform: linux/arm64

  app:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      ENV: prod
      DB: mariadb
      DB_USER: root
      DB_PASSWORD: masterroot
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: fast_api_tc_psn
    ports:
      - "8000:8000"
    # volumes:
    #   - .:/app
    command: ["bash", "-c", fastapi run src/main.py --port 8000 "]

volumes:
  db_data: